conda-forge/llvmdev-feedstock

- .travis.yml
- ci_support/run_docker_build.sh
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
This also detects the CPU count of the container being used for the build.
> Simplify bld.bat

- recipe/meta.yaml
Fixes to the build feature logic.
Only merge after files are removed from the conda-forge channel as per discussion in #14.
> Cling-patches

- recipe/build.sh
- recipe/meta.yaml
> Try 9.0.0.rc2

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/win_target_platformwin-64.yaml
- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Remove mattwala from maintainers

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/osx_arm64_.yaml
- README.md
- conda-forge.yml
- recipe/build.sh
> Enable osx-arm64 for 5.x

- recipe/meta.yaml
- recipe/patches/llvm-config-no-libLLVM.diff
> Don't link libLLVM.dylib to llvm-config

- recipe/meta.yaml
- recipe/patches/pass-through-qemu-ld-prefix.diff
> pass through SDKROOT as well

- recipe/meta.yaml
> fix lit entry_point

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_variantcling_v0.9.yaml
- .ci_support/linux_64_variantdefault.yaml
- .ci_support/linux_aarch64_variantcling_v0.9.yaml
- .ci_support/linux_aarch64_variantdefault.yaml
- .ci_support/osx_64_variantcling_v0.9.yaml
- .ci_support/osx_64_variantdefault.yaml
- .ci_support/osx_arm64_variantcling_v0.9.yaml
- .ci_support/osx_arm64_variantdefault.yaml
- .ci_support/win_64_variantcling_v0.9.yaml
- .ci_support/win_64_variantdefault.yaml
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- build-locally.py
- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/patches/cling_v0.9/0001-Enable-unicode-output-on-terminals.patch
- recipe/patches/cling_v0.9/0002-Fix-the-compilation.patch
- recipe/patches/cling_v0.9/0003-Make-datamember-protected.patch
- recipe/patches/cling_v0.9/0004-Work-around-inconsistency-of-std-llvm-is_trivially_c.patch
> Adding a cling variant to llvm 9.x

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_ppc64le_variantcling_v0.9.yaml
- .ci_support/linux_ppc64le_variantdefault.yaml
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Build llvmdev 9.x for ppc64le

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_variantcling_v0.9.yaml
- .ci_support/linux_64_variantdefault.yaml
- .ci_support/linux_aarch64_variantcling_v0.9.yaml
- .ci_support/linux_aarch64_variantdefault.yaml
- .ci_support/linux_ppc64le_variantcling_v0.9.yaml
- .ci_support/linux_ppc64le_variantdefault.yaml
- .ci_support/osx_64_variantcling_v0.9.yaml
- .ci_support/osx_64_variantdefault.yaml
- .ci_support/win_64_variantcling_v0.9.yaml
- .ci_support/win_64_variantdefault.yaml
- .gitattributes
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- build-locally.py
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> [9.x] Fix ppc64le build

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .gitattributes
- .github/workflows/automerge.yml
- .github/workflows/webservices.yml
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- build-locally.py
- recipe/meta.yaml
Picking up https://github.com/conda-forge/llvmdev-feedstock/commit/abfc1265f9d3991528c955982cf28ef513d41519 for 11.x branch.
> Add libxml2 fix; rerender

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/run_osx_build.sh
- recipe/bld.bat
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/install_llvm.sh
- recipe/meta.yaml
- recipe/patches/0001-pass-through-QEMU_LD_PREFIX-SDKROOT.patch
- recipe/patches/0002-Don-t-link-libLLVM.dylib-to-llvm-config.patch
> Build dev commit for Tensorflow 2.8.0

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Attempting to fix some Windows issue see with `llvmlite` per this comment ( https://github.com/conda-forge/llvmlite-feedstock/pull/68#issuecomment-1292883024 ).
<hr>
Checklist
> Rebuild LLVM 11.1

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/win_64_.yaml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Checklist
Trying to get a build with which `llvmlite` builds on Windows.
See
- https://github.com/conda-forge/llvmlite-feedstock/pull/68#issuecomment-1292480034 ff
- https://github.com/conda-forge/llvmlite-feedstock/pull/68#issuecomment-1293550946
> Rebuild 11.x with vs2017

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .circleci/config.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
Fixes #188 
This PR was somehow not (yet) regenerated by the bot. Other like https://github.com/conda-forge/clangdev-feedstock/pull/192 were already.
Checklist
> llvmdev 15.0.4

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .circleci/config.yml
- .github/workflows/automerge.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
- recipe/patches/no-windows-symlinks.patch
> no symlinks on windows (14.x)

- recipe/meta.yaml
> bump to 16.0.0.rc2

- recipe/meta.yaml
- recipe/patches/0003-restore-macos-10.9-support.patch
> restore 10.9 support

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libxml2211.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- README.md
- conda-forge.yml
- recipe/install_llvm.bat
- recipe/meta.yaml
Backport #210 & #214, forward-port #199
Closes #221
> [15.x] Lit entry point, diaguids fix, libxml2

- .azure-pipelines/azure-pipelines-osx.yml
- recipe/meta.yaml
> llvmdev 18.1.5

- .ci_support/linux_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- conda-forge.yml
- recipe/meta.yaml
Rebuild again from main (https://github.com/llvm/llvm-project/commit/edf5782f1780f480c3ae3fc0a44bf5432f9aa48b) after fix for flang (https://github.com/llvm/llvm-project/commit/a2d340ba161fe48ee4ff736c6e7877038a7388cd) landed upstream
> [dev] llvmdev 19.0.0.dev0, take 2

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- recipe/meta.yaml
- recipe/patches/0002-lljit-respect-codemodel.patch
> Fix LLJIT ignoring the CodeModel setting

- recipe/install_llvm.bat
- recipe/install_llvm.sh
- recipe/meta.yaml
> version suffixed LLVM tools

- recipe/meta.yaml
- recipe/patches/0001-pass-through-QEMU_LD_PREFIX-SDKROOT.patch
- recipe/patches/0002-llvm-LLVM_ENABLE_RUNTIMES-flang-rt.patch
- recipe/patches/0003-ExecutionEngine-reinstate-necessary-include.patch
Another update to the upstream PR happened (newer upstream `main` merged); also windows builds needed fixing.
> [dev] update build from main for testing flang-rt

- .scripts/run_docker_build.sh
- build-locally.py
- recipe/meta.yaml
> llvmdev v20.1.2

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_variantroot_63406.yaml
- .ci_support/linux_aarch64_variantroot_63406.yaml
- .ci_support/linux_ppc64le_variantroot_63406.yaml
- .ci_support/osx_64_variantroot_63406.yaml
- .ci_support/osx_arm64_variantroot_63406.yaml
- .gitignore
- .scripts/run_docker_build.sh
- README.md
- build-locally.py
- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/patches/root/0003-UPSTREAM-ADT-Add-cstdint-to-SmallVector-101761.patch
- recipe/patches/root/0004-UPSTREAM-Add-missing-include-to-X86MCTargetDesc.h-12.patch
Checklist
For now this is WIP, I am testing locally that these changes also result in a valid build of the root-feedstock
> Add patches for ROOT 6.34.06

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/run_docker_build.sh
- .scripts/run_win_build.bat
- README.md
- build-locally.py
- conda-forge.yml
- recipe/meta.yaml
- recipe/patches/0001-pass-through-QEMU_LD_PREFIX-SDKROOT.patch
Check in on upstream main branch; about ~1 month before rc1; 3 months after #320
> [dev] llvmdev v21.0.0.dev2

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/libxml2214.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Bot seems to be waiting for phantom parents.
> [main] Rebuild for libxml2 2.14
